// Package skills implements skill discovery, loading, and registration.
//
// A skill is a slash-command (/commit, /review) that expands into a prompt
// that the model processes. Skills are defined as markdown files with YAML
// frontmatter and are discovered from:
//
//	~/.forge/skills/     — user-global skills
//	.forge/skills/       — project-local skills
//
// Built-in skills are registered at startup via RegisterBundledSkill.
package skills

import (
	"context"
	"sync"
)

// ContextMode controls how a skill executes.
type ContextMode string

const (
	// ContextInline runs the skill by injecting its prompt into the current
	// conversation. This is the default.
	ContextInline ContextMode = "inline"

	// ContextFork runs the skill in an isolated sub-agent. Not yet implemented
	// in Forge; skills with this context fall back to inline execution.
	ContextFork ContextMode = "fork"
)

// Skill represents a single discoverable skill.
type Skill struct {
	// Name is the canonical identifier, e.g. "commit" or "review-pr".
	// Derived from the markdown filename (no .md extension).
	Name string

	// Description is a short summary shown in tool listings and search.
	Description string

	// WhenToUse is an optional hint that tells the model when to invoke this skill.
	WhenToUse string

	// AllowedTools is the optional set of tool names permitted while running this
	// skill. Empty means all tools are allowed.
	AllowedTools []string

	// Context is the execution mode: "inline" (default) or "fork".
	Context ContextMode

	// UserInvocable is true (default) when the skill is accessible via the
	// slash-command interface. Set to false for internal/model-only skills.
	UserInvocable bool

	// Source describes where the skill was loaded from ("bundled", "user", "project").
	Source string

	// Prompt is the skill's prompt content. For file-based skills this is the
	// markdown body (everything after the frontmatter). For bundled skills it
	// is generated by the Prompt function.
	Prompt func(args string) string

	// Execute, when non-nil, is called by SkillTool instead of expanding Prompt.
	// This allows skills like /forge to run a full orchestrator pipeline rather
	// than injecting a text prompt.
	//
	// The execCtx parameter is the raw execution context (*tools.ToolContext),
	// passed as interface{} to avoid an import cycle (tools imports skills).
	// Type-assert at the use site: execCtx.(*tools.ToolContext).
	Execute func(ctx context.Context, args string, execCtx interface{}) error
}

// SkillRegistry stores all discovered and registered skills.
// Safe for concurrent access.
type SkillRegistry struct {
	mu     sync.RWMutex
	skills map[string]*Skill // keyed by Name
}

// NewRegistry creates an empty SkillRegistry.
func NewRegistry() *SkillRegistry {
	return &SkillRegistry{skills: make(map[string]*Skill)}
}

// Register adds or replaces a skill. The last writer wins when the same name
// is registered from multiple sources (bundled < user < project).
func (r *SkillRegistry) Register(s *Skill) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.skills[s.Name] = s
}

// Lookup returns the skill with the given name, or nil if not found.
// Leading slashes in name are stripped before lookup.
func (r *SkillRegistry) Lookup(name string) *Skill {
	n := stripLeadingSlash(name)
	r.mu.RLock()
	defer r.mu.RUnlock()
	return r.skills[n]
}

// All returns a snapshot of all registered skills in no guaranteed order.
func (r *SkillRegistry) All() []*Skill {
	r.mu.RLock()
	defer r.mu.RUnlock()
	out := make([]*Skill, 0, len(r.skills))
	for _, s := range r.skills {
		out = append(out, s)
	}
	return out
}

// Len returns the number of registered skills.
func (r *SkillRegistry) Len() int {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return len(r.skills)
}

func stripLeadingSlash(name string) string {
	if len(name) > 0 && name[0] == '/' {
		return name[1:]
	}
	return name
}
